version: '3.8'
services:
  springboot-server:
    image: tungpd35/flight-ticket:v1.0.0
    container_name: springboot-docker
    ports:
      - "8081:8080"
    volumes:
      - ./:/app
    networks:
      - backend
  mysqlserver:
    container_name: "mysqlserver"
    image: mysql:8.0
    ports:
      - "3310:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=tung1182002
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=tungpd
      - MYSQL_PASSWORD=tung182002
      - MYSQL_DATABASE=db
    volumes:
      - mysqlserver_data:/var/lib/mysql
      - mysqlserver_config:/etc/mysql/conf.d
    networks:
      - backend
networks:
  backend:
    name: mysqlnet
volumes:
  mysqlserver_data:
  mysqlserver_config: